# Generated by Django 4.1 on 2023-04-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_level',
            field=models.CharField(choices=[('CU', 'Customer'), ('TW', 'Till Worker'), ('CR', 'Car Retrieval Specialist'), ('MA', 'Manager')], default='CU', max_length=2),
        ),
    ]
