# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEmployeeGettingPaid():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_employeeGettingPaid(self):
    # Test name: Employee Getting Paid
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://127.0.0.1:8000/")
    # 2 | setWindowSize | 1848x1053 | 
    self.driver.set_window_size(1848, 1053)
    # 3 | click | linkText=Login | 
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    # 4 | click | name=username | 
    self.driver.find_element(By.NAME, "username").click()
    # 5 | type | name=username | carperson
    self.driver.find_element(By.NAME, "username").send_keys("carperson")
    # 6 | click | name=password | 
    self.driver.find_element(By.NAME, "password").click()
    # 7 | type | name=password | password
    self.driver.find_element(By.NAME, "password").send_keys("password")
    # 8 | click | css=label:nth-child(6) | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(6)").click()
    # 9 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 10 | click | id=navbarDarkDropdownMenuLink | 
    self.driver.find_element(By.ID, "navbarDarkDropdownMenuLink").click()
    # 11 | click | linkText=Staff | 
    self.driver.find_element(By.LINK_TEXT, "Staff").click()
    # 12 | click | linkText=Log Hours Worked | 
    self.driver.find_element(By.LINK_TEXT, "Log Hours Worked").click()
    # 13 | click | id=inputHours | 
    self.driver.find_element(By.ID, "inputHours").click()
    # 14 | type | id=inputHours | 20
    self.driver.find_element(By.ID, "inputHours").send_keys("20")
    # 15 | click | css=.btn-secondary | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
    # 16 | mouseDownAt | css=body | 1575,179
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 17 | mouseMoveAt | css=body | 1575,179
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | mouseUpAt | css=body | 1575,179
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 19 | click | css=body | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 20 | click | id=navbarDarkDropdownMenuLink | 
    self.driver.find_element(By.ID, "navbarDarkDropdownMenuLink").click()
    # 21 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
