# Generated by Django 4.1 on 2023-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='plateNumber',
            field=models.CharField(max_length=50),
        ),
    ]
