# Generated by Django 4.1 on 2023-03-11 23:57

from django.db import migrations

def populate_db(apps, schema_editor):
    
    start_date = '2025-01-01'
    end_date = '2025-01-05'
    
    Reservation = apps.get_model('Customer', 'Reservation')
    Car = apps.get_model('Manager', 'Car')
    UserProfile = apps.get_model('UserAuth', 'UserProfile')
    
    car1 = Car.objects.get(pk=1)
    car2 = Car.objects.get(pk=2)
    
    new_admin = UserProfile.objects.get(pk=1)
    new_customer = UserProfile.objects.get(pk=2)
    
    res1 = Reservation(car=car1, user=new_admin, startDate=start_date, endDate=end_date)
    res2 = Reservation(car=car2, user=new_customer, startDate=start_date, endDate=end_date)
    res1.save()
    res2.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
