# Generated by Django 4.1 on 2023-03-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='renterID',
        ),
    ]
