# Generated by Django 4.1 on 2023-02-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('gasFillPercent', models.IntegerField()),
                ('plateNumber', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to="cars")),
                ('lowjacked', models.BooleanField(default=False)),
            ],
        ),
    ]
