# Generated by Django 4.1 on 2023-02-25 19:24

from django.db import migrations

def populate_db(apps, schema_editor):

    # CUSTOM DATA MIGRATIONS FOR CARS
    Car = apps.get_model('Manager', 'Car')
    
    car1 = Car(make='Honda', model='Civic', year='1993', plateNumber='aaaaa', image='cars/civic.png', gasFillPercent=100)
    car1.save()
    
    car2 = Car(make='Ford', model='Cobra', year='1993', plateNumber='bbbbb', image='cars/cobra.png', gasFillPercent=100)
    car2.save()
    
    car2 = Car(make='Isuzu', model='Trooper', year='1999', plateNumber='ccccc', image='cars/trooper.png', gasFillPercent=100)
    car2.save()
    
    car3 = Car(make='Lamborghini', model='Diablo', year='1996', plateNumber='ddddd', image='cars/diablo.png', gasFillPercent=100)
    car3.save()
    
    car4 = Car(make='BMW', model='M-5', year='1997', plateNumber='eeeee', image='cars/bmw.png', gasFillPercent=100)
    car4.save()
    
    car5 = Car(make='Dodge', model='Viper', year='1994', plateNumber='fffff', image='cars/viper.png', gasFillPercent=100)
    car5.save()

    car6 = Car(make='Jeep', model='Cherokee', year='1999', plateNumber='gggggg', image='cars/jeep.png', gasFillPercent=100)
    car6.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
