# Generated by Django 4.1 on 2023-02-25 19:24

from django.db import migrations

def populate_db(apps, schema_editor):
    Car = apps.get_model('Manager', 'Car')
    
    car1 = Car(make='Honda', model='civic', year='1993', plateNumber='aaaaa', photoID='a1a1a1', gasFillPercent=100)
    car1.save()
    
    car2 = Car(make='Honda', model='civic', year='1993', plateNumber='bbbbb', photoID='b2b2b2', gasFillPercent=100)
    car2.save()
    
    car2 = Car(make='Honda', model='civic', year='1993', plateNumber='ccccc', photoID='c3c3c3', gasFillPercent=100)
    car2.save()
    
    car3 = Car(make='Honda', model='civic', year='1993', plateNumber='ddddd', photoID='d4d4d4', gasFillPercent=100)
    car3.save()
    
    car4 = Car(make='Honda', model='civic', year='1993', plateNumber='eeeee', photoID='e5e5e5', gasFillPercent=100)
    car4.save()
    
    car5 = Car(make='Honda', model='civic', year='1993', plateNumber='fffff', photoID='f6f6f6', gasFillPercent=100)
    car5.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
