# Generated by Django 4.1.2 on 2023-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(default='No Location Yet', max_length=150),
        ),
    ]
