# Generated by Django 4.1.2 on 2023-04-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_car_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
