# Generated by Django 4.1 on 2023-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_car_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(default='No Location Yet', max_length=150),
        ),
    ]
